// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:vitalinguu/core/data/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LanguageLocaleAdapter());
    registerAdapter(TopicAdapter());
    registerAdapter(TopicAssessmentAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LanguageLocaleAdapter());
    registerAdapter(TopicAdapter());
    registerAdapter(TopicAssessmentAdapter());
  }
}
